#variable at task level
- name: Variables from PLAY level
  hosts: localhost
  vars: 
    Course: "DevOps"
    Trainer: "Dastagiri"
    Dureation: "110HRS"
  tasks:
  - name: Can you check this Variables 
    Course: "AWS Course "DevOps""
    ansible.builtin.debug:
      msg: "Hi, I'm learing {{Course}}, trainer is {{Trainer}} and Dureation is {{Dureation}}"
