#variable at task level
- name: Variables from PLAY level
  hosts: localhost
  vars: 
    Course: "DevOps"
    Trainer: "Dastagiri"
    Dureation: "110HRS"
  tasks:
  - name: Can you check this Variables 
      var: #task level
      Course: "AWS Course "DevOps""
    ansible.builtin.debug:
      msg: "Hi, I'm learning {{Course}}, trainer is {{Trainer}} and Dureation is {{Dureation}} now"
